### ISSUE TITLE
[Question] Changing views using iron:router

### ISSUE THREAD

**Issue by guilhermedecampo** [DispatchMe/meteor-short-url#2]
Hi @raix ! 
So glad I found your package. Looks awesome! 

As far as I could understand, for changing to the right view/template I'll have to add the logic on the redirect emitter, right?

But for example with iron:router the method `go` can't be called in the server side, how should I proceed?

**Comment by guilhermedecampo** [comment]
Hey just saw the script tag on `redirect.template.html` !
Nice! :tada:

**Comment by raix** [comment]
Thanks :)
